#!/bin/bash
source "$(dirname "$0")/_uab-internal.sh"

function usage () {
    EXEC_NAME="$(basename $0)"
    cat << EOF
Usage: $EXEC_NAME <git repo>
EOF
}

if [ $# -lt 1 ]; then
    usage >& 2
    exit 2
fi

git clone --progress --bare "$1" git && cp "$UAB_SAMPLE_CONF" "$UAB_CONF_XML"
